### ISSUE TITLE
Is M1 Max supported?

### ISSUE THREAD

**Issue by danio0701** [verygenericname/SSHRD_Script#103]
Gaster freeze with any device at

usb_timeout: 10
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Stage: SPRAY

**Comment by verygenericname** [comment]
Gaster problem, make an issue over there
