### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by baimour** [verygenericname/SSHRD_Script#106]
./sshrd.sh https://updates.cdn-apple.com/2021WinterFCS/fullrestores/002-05523/A1FB133D-E3C8-44C7-946E-D7C5FEDDE663/iPhone_4.0_64bit_12.5.5_16H62_Restore.ipsw

[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: null
Error init failed
[-] An error occurred

Is there a way to solve？

**Comment by verygenericname** [comment]
version not link
./sshrd.sh 12.5.5

**Comment by baimour** [comment]
> 版本不是链接
> ./sshrd.sh 12.5.5

ok thank you, there is another problem, it cannot be mounted on the 5s 12 system
