### ISSUE TITLE
iPad Air 2 mount_filesystems permission Denied

### ISSUE THREAD

**Issue by ICH525** [verygenericname/SSHRD_Script#109]
![Untitled](https://user-images.githubusercontent.com/116790886/198214344-b4a852bd-0774-493a-8aa1-648b12defa72.jpg)

do you guys face this isssue.. I am getting it right now. anybody knows how to fix it...

**Comment by ICH525** [comment]
I fix it with new update sshrd ramdisk thanks

**Comment by delacroix0815** [comment]
Still the same issue with iPadOS 15.7.3 - iPad Air 2 A8X. Any fixes?
