### ISSUE TITLE
Full Root Access?

### ISSUE THREAD

**Issue by bthedorff** [verygenericname/SSHRD_Script#11]
OS: Mac OS Monterey 12.5
Device: iPhone 8 (Global)
IOS: Was 15.6 but downgraded to 14.8 using sunst0rm (also tried 14.4.2)
Possible Issue: Not having full root access?

When I attempt to move/edit a file to` /mnt2/mobile/containers/Data/Application `or `/mnt2/containers/Bundle/Application` I always get "`operator not permitted`. I have tried through the terminal, Cyberduck and Termius. I have tried giving all folders needed all permissions using chmod 777. Any ideas?

**Comment by verygenericname** [comment]
Some places are protected on the filesystem, like mobile
