### ISSUE TITLE
Mac T2 Panic on Data Partition mount

### ISSUE THREAD

**Issue by alhaithammsar** [verygenericname/SSHRD_Script#113]
Hi, so i got ssh to work with your ramdisk 
but when running the exec to mount all partitions terminal freeze, however when I run the commands Manually everything goes smooth until last command
-Root partition mounted on mnt1
-SEP mounted on mnt6
-.gl file mounted on mnt7
-doing seputil —gigalocker works
-doing —load SEP  works
-Mounting data partition on mnt2 freeze ssh & result in reboot after 1-2 minutes 

tried on multiple T2 Macs with different BridgeOS v6 installed on them & doing different Ramdisks from bridgeOS versions
No luck on Data mount,
however T2 Mac with BridgeOS 5.4 doing same commands & Data gets mounted No issue! 

I hope you can help in the Data mount

if you want to chat here is my Tėlgram @SDunlocks_91

**Comment by verygenericname** [comment]
I dont have a T2 mac in person to see why this is happening, sorry

**Comment by alhaithammsar** [comment]
i was able to fix this issue and got /var to mount on mnt2
