### ISSUE TITLE
(base) MacBook-Pro:SSHRD_Script gpu$ sudo ./sshrd.sh 15.7

### ISSUE THREAD

**Issue by DjalilDev** [verygenericname/SSHRD_Script#115]
(base) MacBook-Pro:SSHRD_Script gpu$ sudo ./sshrd.sh 15.7
Password:
[-] An error occurred
(base) MacBook-Pro
![Screen Shot 2022-11-08 at 2 05 59 AM](https://user-images.githubusercontent.com/62681075/200448937-8ca9aef7-c7ac-48f8-b7ba-ba1520a95f1a.png)
:SSHRD_Script gpu$

**Comment by verygenericname** [comment]
Old macOS version
