### ISSUE TITLE
Can't boot into SSH

### ISSUE THREAD

**Issue by bthedorff** [verygenericname/SSHRD_Script#13]
OS: Mac OS Monterey 12.5
Device: iPhone 8 (Global)
IOS: 15.6
Issue: Not able to boot into SSH mode anymore. I have done a git pull and retried numerous times. I have tried both linking to iOS 14.8 and 15.6 IPSW both with and without blobs from 15.6. I have also tried using my master to pwn, the built in pwn and ipwnder-lite (my usual go to that works). When I try `./sshrd.sh boot` while pwned, there is no output given, it just ends. 

Below is how it ends. Idk if the usb_time is an error or not. 
`100% [===================================================================================================>]
download succeeded
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:001129EE08D3A02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[ipwnder]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.`

**Comment by verygenericname** [comment]
place the device into DFU from recovery, delete my script and reclone it too. Don't pwn beforehand.

**Comment by bthedorff** [comment]
I've never had to go into recovery first (this or any other programs) but I did try that as well. However, from recovery every time it went straight to rebooting. From recovery, once the screen goes dark I hold the vol down button and side button for 5 seconds then remove the side button but it reboots. I also tried the power button for 10 seconds then vol and power for 5 then let go of the power and still reboots. Any suggestions on that so I can give it a proper go?

**Comment by verygenericname** [comment]
use this: https://cdn.discordapp.com/attachments/779844089196576809/990576297367445555/a11dfu.sh

**Comment by bthedorff** [comment]
You really are awesome! The script itself didn't work for me but looking at it, I was holding the power button down first when I should have just skipped to holding the vol down and side button. I tried it in my original git pull and it did not work. After renaming the original and doing a new git clone it worked. Thanks so much!

**Comment by verygenericname** [comment]
did ./sshrd.sh boot work first try after creating the ramdisk

**Comment by bthedorff** [comment]
> did ./sshrd.sh boot work first try after creating the ramdisk

Yes it did after doing git clone again. Did not work in my original folder I git cloned weeks ago
