### ISSUE TITLE
./sshrd.sh boot not working

### ISSUE THREAD

**Issue by 0x8ff** [verygenericname/SSHRD_Script#136]
I'm trying to get 14.3 blobs from my bootlooping iPhone X, and I can get ``./sshrd.sh 14.3`` to work but the command after that ``./sshrd.sh boot`` causes my iPhone X to get kicked back into Recovery Mode. Idk what to do :P

**Comment by 0x8ff** [comment]
it seems to be an issue on my end

**Comment by badger200** [comment]
I have a IPad Pro 1st gen A9X with dead NAND and have desperately been hoping to recover data from an SSH RAMDISK. Can it still be read?

**Comment by 0x8ff** [comment]
> I have a IPad Pro 1st gen A9X with dead NAND and have desperately been hoping to recover data from an SSH RAMDISK. Can it still be read?


@badger200 is your device able to boot into DFU from Recovery Mode?

**Comment by 0x8ff** [comment]
(you can use my script to help boot into DFU from Recovery Mode)

https://gist.github.com/0x8ff/9cef409d3b584514046fcffdd7639ca3
