### ISSUE TITLE
[iPhone 8 Plus - GSM] Unable to connect to device

### ISSUE THREAD

**Issue by tygerxqt** [verygenericname/SSHRD_Script#137]
So the situation as it stands is, I have a iPhone 8 plus (GSM) running 16.2, I'm trying to wipe my device clean so I can install the palera1n jailbreak. I tried DFU restoring using iTunes however, my device would boot normally when iTunes would try and connect to the device, it would then spit out an error code of "4016". I tried using different cables, computers, but it all returned the same thing. I was losing hope until I found your script.

I'm currently trying to install the ramdisk using the command `./sshrd.sh 16.2` however that seems to return:
```
[*] Getting device info and pwning... this may take a second
ERROR: Unable to connect to device
ERROR: Unable to connect to device
ERROR: Unable to connect to device
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9
```

I tried running `./sshrd 16.1` and `./sshrd 16` however they all returned the same error.
I also tried using two different OS (Ubuntu and Arch), two different computers, and two different cables in different combinations but to no avail.

Is there anyway I could resolve this issue?
Thank you for your time.

**Comment by tygerxqt** [comment]
I forgot to mention, I did run `sudo systemctl stop usbmuxd` and `sudo usbmuxd -f -p`.

**Comment by rustybrozen** [comment]
same problem, just have solved by adding sudo before it

**Comment by tygerxqt** [comment]
@rustybrozen Did you put sudo before `./sshrd 16`?
