### ISSUE TITLE
hdiutil: resize: failed. Invalid argument (22)

### ISSUE THREAD

**Issue by DasEric** [verygenericname/SSHRD_Script#139]
When I try to use the script I get this error I have reset my iPhone several times and tried again but I get this error again.
(iPhone 8 Plus, iOS 16.2)

here is a part of the output of the console:

[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 16 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180032cb0 : 000080d2
applying patch=0x180032d54 : 000080d2
applying patch=0x1800348cc : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 16 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180032cb0 : 000080d2
applying patch=0x180032d54 : 000080d2
applying patch=0x18001e204 : 000080d2c0035fd6
applying patch=0x18001e25c : 000080d2c0035fd6
applying patch=0x180062378 : 000080d2c0035fd6
applying patch=0x1800348cc : 200080d2
applying patch=0x180035f8c : 381d0d10
applying patch=0x180050330 : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x18003acb8 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8792 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0xa2af54
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x12e869c
get_amfi_out_of_my_way_patch: Patching AMFI at 0x12e1a5c
main: Writing out patched file to work/kcache.patched...
main: Quitting...
0x12e1a78 0xfffffffd 0xffffffe0
0x12e1a79 0x7b 0x3
0x12e1a7a 0xffffffbf 0x0
0x12e1a7b 0xffffffa9 0x32
0x12e1a7c 0xfffffffd 0xffffffc0
0x12e1a7e 0x0 0x5f
0x12e1a7f 0xffffff91 0xffffffd6
krnl
dtre
rtsc
rdsk
hdiutil: resize: failed. Invalid argument (22)
[-] An error occurred

**Comment by szubert** [comment]
I have the same issue on my iPad 5th gen, ios 16.2
