### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by z3ven** [verygenericname/SSHRD_Script#144]
I cloned all how you yelled and error occurred:
``` git clone https://github.com/verygenericname/SSHRD_Script --recursive ```
```chmod a+x /SSHRD_Script/sshrd.sh```
```./SSHRD_Script/sshrd.sh 15.0```
and after: 
```
fatal: not a git repository (or any of the parent directories): .git
[-] An error occurred
```

**Comment by iDev27** [comment]
Always run from within the `SSHRD_Script` directory.

`$ cd SSHRD_Script`
`$ ./sshrd.sh 15.0`
