### ISSUE TITLE
Ssh iphone 6

### ISSUE THREAD

**Issue by trunggc** [verygenericname/SSHRD_Script#16]
How mount disk iphone 6 and mount mnt4 sir!!!

**Comment by verygenericname** [comment]
mount_filesystems

**Comment by trunggc** [comment]
> mount_filesystems

I use it but don't mount sir

**Comment by verygenericname** [comment]
need more information, can you tell me what happens when you try to use it? what version is the device on?

**Comment by trunggc** [comment]
> need more information, can you tell me what happens when you try to use it? what version is the device on?

![image](https://user-images.githubusercontent.com/83798330/186425480-944f485f-781d-4eea-8351-ef38aeb3b26d.jpeg)

List /dev/ rdisk0s1 not disk0s1

**Comment by verygenericname** [comment]
ls /mnt1

**Comment by trunggc** [comment]
> ls /mnt1

![image](https://user-images.githubusercontent.com/83798330/186426684-32f9e7fa-aec6-4760-9b26-7d617e5bc296.jpeg)
Nothing sir ios 12.0 and ios 12.5.5 iphone 6

**Comment by verygenericname** [comment]
might be in a different location, i will fix the script when i have time
you can manually mount for now

**Comment by verygenericname** [comment]
mount_apfs /dev/disk0s1s1 /mnt1
/usr/libexec/seputil --load /mnt1/usr/standalone/firmware/sep-firmware.img4
mount_apfs /dev/disk0s1s2 /mnt2

**Comment by trunggc** [comment]
> mount_apfs /dev/disk0s1s1 /mnt1
> 
> /usr/libexec/seputil --load /mnt1/usr/standalone/firmware/sep-firmware.img4
> 
> mount_apfs /dev/disk0s1s2 /mnt2

You have telegam???

**Comment by verygenericname** [comment]
refer to issue above please
