### ISSUE TITLE
Can u add sep ?

### ISSUE THREAD

**Issue by ranzhie07** [verygenericname/SSHRD_Script#160]
Hi can u add sep.img4

**Comment by dfas5fd498** [comment]
ok

**Comment by dfas5fd498** [comment]
> 还行

你是如何实现的，我向你请教

**Comment by 654sd** [comment]
> > 还行
> 
> 你是如何实现的，我向你请教

I want to know how to make SEP

**Comment by verygenericname** [comment]
Not needed, use palesshrd branch

**Comment by 654sd** [comment]
> 不需要，使用palesshrd分支

我想制作出iOS16-16.5系统以上加载不崩溃循环的ramdisk所以我需要知道如何生产sep

**Comment by 654sd** [comment]
> Not needed, use palesshrd branch

I very much hope that the sshrd project can update the memory boot to support iOS13-16.5, and solve the system crash caused by 16 systems, but I have to say that the current sshrd project has been very good, but for me such a small white, secondary development is still a lot of difficulty
