### ISSUE TITLE
Bootloop ios 16.4

### ISSUE THREAD

**Issue by ranzhie07** [verygenericname/SSHRD_Script#161]
Hello there's an bootloop issue in ios16.4 for a11 can u fix?

**Comment by trunggc** [comment]
Kernelcache ios 16.4 but i don't patcher it

**Comment by ethhab** [comment]
Kernel needs additional patches

**Comment by trunggc** [comment]
You have???

**Comment by ethhab** [comment]
Yes i have.
contact me t.me/ethhab
