### ISSUE TITLE
[-] An error occurred

### ISSUE THREAD

**Issue by CopacoGuy** [verygenericname/SSHRD_Script#169]
After running sudo bash for sshrd.sh, I type my password and just says "[-] An error occurred". I installed homebrew, libidevice mobile and recovery along with python. I re-installed and still get the error. I don't even get to the DFU prompt, just that error.
Running 2016 MacBook Pro Mojave 10.14.6. Help really appreciated.

**Comment by verygenericname** [comment]
Need to install curl from homebrew

**Comment by macaty** [comment]
curl -k -sLO https://nightly.link/verygenericname/gaster/workflows/makefile/main/gaster-"$oscheck".zip
use -k to fix the old curl version bug
