### ISSUE TITLE
iPad partition mount problem

### ISSUE THREAD

**Issue by matdanh** [verygenericname/SSHRD_Script#17]
I tried iPad gen 6, gen 7, iPad pro2 12.9, iPad Pro 10.5 all have no system partition to mount as shown in the picture
Please help me fix this problem, thank you!

![933be4c5a71862463b09](https://user-images.githubusercontent.com/111832770/186454841-c4ea761a-dfd5-47ed-a131-228f393a2e98.jpg)

**Comment by verygenericname** [comment]
I’ll have to take a look into this

**Comment by verygenericname** [comment]
can you try again
reclone it

**Comment by matdanh** [comment]
> can you try again reclone it

try again done, tks bro
