### ISSUE TITLE
mount iPad Air2 and mini4

### ISSUE THREAD

**Issue by matdanh** [verygenericname/SSHRD_Script#19]
I test 2 iPad model air2 & mini4 have partition problem: Permission denied
Can this problem be fixed bro?

same here: https://www.reddit.com/r/setupapp/comments/vc30t0/ipad_air_2_success_boot_on_ramdisk_but_cannot/

> localhost:~ root# /sbin/mount_apfs /dev/disk0s1s4 /mnt4
> mount_apfs: volume could not be mounted: Permission denied
> localhost:~ root# /sbin/mount_apfs /dev/disk0s1s5 /mnt5
> mount_apfs: volume could not be mounted: Permission denied
> localhost:~ root# /sbin/mount_apfs /dev/disk0s1s3 /mnt7
> mount_apfs: volume could not be mounted: Permission denied
> localhost:~ root# /usr/libexec/seputil --gigalocker-init
> seputil: Gigalocker not needed on platform, skipping initialization
> <xec/seputil --load /mnt4/*/usr/standalone/firmware/sep*                     
> seputil: can't open '/mnt4/*/usr/standalone/firmware/sep*', errno: No such file or directory(2)
> seputil: rejecting zero-byte firmware
> seputil: failed to load /mnt4/*/usr/standalone/firmware/sep* in  mode
> localhost:~ root# /sbin/mount_apfs /dev/disk0s1s2 /mnt2
> mount_apfs: volume could not be mounted: Permission denied
> localhost:~ root#

![89dda854c3b106ef5fa0](https://user-images.githubusercontent.com/111832770/186657520-e254ed61-64ce-470e-be5b-bc94a16f5f7c.jpg)

**Comment by chaosseo** [comment]
14.3  change  ssh.tar

/System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s3
/System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s4
/System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s5
/System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s6
/System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s7

**Comment by matdanh** [comment]
> 14.3 change ssh.tar
> 
> /System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s3 /System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s4 /System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s5 /System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s6 /System/Library/Filesystems/apfs.fs/apfs.util -p /dev/disk0s1s7

This is to fix for iPad Air2 mount but only-read?

**Comment by verygenericname** [comment]
Those just tell you the Partition names

**Comment by trunggc** [comment]
Cpid chip 7000 and 7001 iphone-ipad don't mount mnt

**Comment by verygenericname** [comment]
i think i know a fix.

**Comment by verygenericname** [comment]
need extra patch kernel64patcher

**Comment by verygenericname** [comment]
possibly happens on iphone 6 too

**Comment by verygenericname** [comment]
happens on all a7-a8x devices

**Comment by verygenericname** [comment]
UPDATE: FOUND A TEMP FIX FOR A7-A8X DEVICES, TOMORROW I WILL IMPLEMENT A KERNEL PATCH INSTEAD, FOR NOW I WILL IMPLEMENT A TEMP FIX.

**Comment by verygenericname** [comment]
please try the temporary fix

**Comment by verygenericname** [comment]
this looks like it only works for 13-14, will do real fix tomorrow

**Comment by matdanh** [comment]
> please try the temporary fix

i have an Air 2 iOS15.6, tested still error with new sshrd.sh
i wait you patch kernel64patcher and retest

**Comment by Stokes83** [comment]
hi bro,

on iphone 8 ios 16 can this tool work on it.

**Comment by Sebastian7700** [comment]
**@verygenericname @matdanh** I’m not sure if this is the same issue, but when I try to run the script on my **iPad Air 2 (iPad5,4-j82ap)**, I’m unable to mount the filesystem.  

I'm using **Ubuntu 22.04 LTS**, and the device is running **iPadOS 9.3.5**. Since **iOS 9.x** Ramdisks were giving me a `Not a mach-o!` error, I used **iOS 12.4** instead. With this, I was able to create a Ramdisk, dump the **.shsh** file, and connect via **SSH**.  

However, my goal was to access the filesystem, and when I run `mount_filesystems`, I get the following error:  

```
sudo bash ./sshrd.sh ssh
localhost:~ root# mount_filesystems
mount_apfs: mount: Inappropriate file type or format
seputil: can't open '/mnt1/usr/standalone/firmware/sep-firmware.img4'
seputil: rejecting zero-byte firmware
seputil: failed to load /mnt1/usr/standalone/firmware/sep-firmware.img4 in  mode
mount_apfs: mount: Inappropriate file type or format
```

The iPad displays this error:

```
dev_init:285: /dev/disk0s1: device accelerated crypto: 1 (compiled @ Jum 22 2019 00:07:51)
dev_init:288: /dev/disk0s1: device_handle block size 4096 blockcount 3870731 features 22 internal apfs_vfsop_mount:1321: unable to mount from /dev/disk0s1s1: 79
```

This issue persists on **iOS 13.5** and **iOS 14.3** as well.  

If anyone has a solution for this, I’d greatly appreciate the help.  
Thanks in advance, and best regards!
