### ISSUE TITLE
iPhone 10,6 init pzb failed

### ISSUE THREAD

**Issue by Biyoni** [verygenericname/SSHRD_Script#22]
I'm getting the message

```
init pzb ../iPhone10,3,iPhone10,6_15.6.1_19G82_Restore.ipsw 

Error init failed

failed
```

Everything preceeding seems to run fine.

I'm running on Linux

**Comment by verygenericname** [comment]
Did you provide a link directly

**Comment by Biyoni** [comment]
Weep sorry didn't notice I mangled the message
There, edited it

**Comment by verygenericname** [comment]
Thats not how it works
what are you trying to do?

**Comment by Biyoni** [comment]
I'm trying to boot the SSH ramdisk?

Better if I post the full log?

**Comment by Biyoni** [comment]
Oh

I see.

Well it's throwing up a progress bar now so I guess that was it.

Thank you!

**Comment by verygenericname** [comment]
did it work

**Comment by Biyoni** [comment]
I got it to boot, it flashed up a bunch of text, then went to an apple logo with a loading bar

When I run iproxy and ssh in though, iproxy spits this out and ssh resets
```
waiting for connection
Requesting connecion to USB device handle 1 (serial: c2e2eec20036f7bf8886bf8e3eec8124ffdda8c4), port 22
Error connecting to device: Success
New connection for 2222->22, fd = 5
```

**Comment by Biyoni** [comment]
After a little while it dumps into ios

**Comment by verygenericname** [comment]
did you recursively clone the repo

**Comment by verygenericname** [comment]
recursively clone the repo and recreate the ramdisk

**Comment by Biyoni** [comment]
I just recloned it recursively, not sure I did last time.

Now the screen with the text has remained but now I'm getting

```
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
```
I know I'm being stupid somewhere thanks for bearing with me lol

**Comment by verygenericname** [comment]
What os are you on on your pc

**Comment by Biyoni** [comment]
Arch Linux,

CPU is Intel 10210U, I believe that matters with checkm8?

**Comment by verygenericname** [comment]
usbmuxd on there is broken, stop the usbmuxd daemon temperarily and start usbmuxd2 from tihmstar for the time being

**Comment by Biyoni** [comment]
That worked, I take it password is that of the phone?

**Comment by Biyoni** [comment]
Ah nevermind, it's alpine
