### ISSUE TITLE
Setting Nonce

### ISSUE THREAD

**Issue by bthedorff** [verygenericname/SSHRD_Script#23]
OS: Mac OS Monterey 12.5
Device: iPhone 8 (Global)
IOS: 15.6.1
I received the following permissions/privilege error when trying to set nonce 

```
localhost:/ root# nvram com.apple.System.boot-nonce=0x1111111111111111
Error setting variable - 'com.apple.System.boot-nonce': (iokit/common) privilege violation.
```

**Comment by verygenericname** [comment]
maybe try a older ipsw, like 14.8

**Comment by verygenericname** [comment]
you know what, im just reverting that change i made a few days ago to remove ibec

**Comment by verygenericname** [comment]
kernel patch is needed for this to work, ugh

**Comment by verygenericname** [comment]
can you run git pull
then recreate the ramdisk, then ./sshrd.sh set-nonce 0x1111111111111111

**Comment by bthedorff** [comment]
Is the nonce supposed to stay set? After setting nonce it immediately reboots then I go back into pwndfu mode and use `irecovery -q` to check the nonce and it is different (doesn't match my blobs). When I repeat and nonce is again different every time?

**Comment by verygenericname** [comment]
yyeah futurerestore is probably better at the nonce part. i cant figure out why it's not writing that ONLY var to the nvram

**Comment by bthedorff** [comment]
Thanks for looking into it for me! I tried a few more times but they didn't get set and saved. Then I decided to use the a11dfu.sh script to do recovery then dfu with futurerestore and it started working right after that.
