### ISSUE TITLE
iPhone6p ssh ok, mount failed

### ISSUE THREAD

**Issue by matdanh** [verygenericname/SSHRD_Script#25]
iPhone 6p iOS 12.5.5 ssh via ramdisk (sshrd.sh)
Everything worked fine until I used the mount_filesystems command (renamed it to mount_party)
and try to enter it manually still error. 
Partitions are always empty
Really need help bro!

![cf86780d90a055fe0cb1](https://user-images.githubusercontent.com/111832770/188120331-b231941c-4af1-4d61-ade1-c55c48ad58f1.jpg)

**Comment by P5-2005** [comment]
did you tried manual, like this : https://github.com/verygenericname/SSHRD_Script/issues/16#issuecomment-1226637130 
? on ios12 seem mount is different

**Comment by verygenericname** [comment]
I can’t figure out why this happens on older NAND devices, need a better kernelpatch

**Comment by trunggc** [comment]
Ios 12 mount mnt2 ok but scp error 9

**Comment by matdanh** [comment]
> Ios 12 mount mnt2 ok but scp error 9

Have you tried cat or cp internally?
Can you share how to mount mnt2?

**Comment by midokof** [comment]
![image](https://user-images.githubusercontent.com/19962819/189519339-3efe6a20-7159-4ba5-bf20-3154553c1b41.jpeg)   6s+ help
