### ISSUE TITLE
Can't ssh into ramdisk

### ISSUE THREAD

**Issue by Uckermark** [verygenericname/SSHRD_Script#26]
First of all, i love your work. This project is amazing. 
It worked fine on my iPhone 6 but i could not manage to use it with my iPad:

After booting to the ramdisk i cannot connect to my iPad. Only thing i can do is to hard reset it.

iPad 5 (iPad 6,11) on iOS 15.5

What i ran:
Installed prerequisites and cloned repo

> ./sshrd.sh https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98156/BB24CD59-96C7-472C-BDFE-B40C0DED2370/iPad_64bit_TouchID_ASTC_14.8_18H17_Restore.ipsw

(iOS 14.8 IPSW)

> ./sshrd.sh boot

Then this appeared on my iPad (sorry for that quality):
![16623976030357368738381432212618](https://user-images.githubusercontent.com/93996544/188493252-eb4d3d1f-976b-4098-bd8d-e6fecd6318d7.jpg)

New terminal window:
> iproxy 2222 22

Original terminal:
> $ssh -p2222 root@localhost
kex_exchange_identification: Connection closed by remote host
Connection closed by 127.0.0.1 port 2222

In iproxy terminal:
> $iproxy 2222 22
Creating listening port 2222 for device port 22
waiting for connection
New connection for 2222->22, fd=5
waiting for connection
Connecting to usbmuxd failed, terminating.

Everything was done on Ubuntu 22.04.1 LTS
So far i have tried to 
- use ipsw 15.6.1 & 14.6 link
- use different usb port
- boot pc from live usb

Thanks in advance,
Uckermark

**Comment by verygenericname** [comment]
stop the usbmuxd system daemon, and compile and run usbmuxd2 from tihmstar, that seems to work
