### ISSUE TITLE
Need to recover data from iPhone 5 iOS 6.1.4 HFS, how to be safe about this?

### ISSUE THREAD

**Issue by badger200** [verygenericname/SSHRD_Script#264]
This iPhone 5 was jailbroken with helix but I eventually filled the disk to the point it caused it to fail to boot. So basically all I need is to mount the system disk r/w and delete some worthless file (or one I can copy back later).

The readme for this project says warning do not use on very old systems! So.... any suggestions?

**Comment by verygenericname** [comment]
This tool only works with 64bit devices, sorry
