### ISSUE TITLE
[Question] Can I install ONE tweak?

### ISSUE THREAD

**Issue by lorenzoferron98** [verygenericname/SSHRD_Script#27]
Hi! I have an iPhone X with iOS 15.6.1 without ANY SHSH blobs saved. I can't jailbreak it unless I do a tethered downgrade to iOS 14.3 with [sunst0rm](https://github.com/mineek/sunst0rm). I want to jailbreak it to ONLY use [Frida](https://github.com/frida/frida/releases/download/15.2.2/frida_15.2.2_iphoneos-arm.deb).

So is it possible to use this script to manually install Frida DEB: copying & pasting its content (modifying FS) over SSH?

Thanks in advance.

**Comment by verygenericname** [comment]
I just stick SpringBoard into a ipa, shove it into sideloadly, tick the "normal install" option, and enable inject tweaks and stick the tweak into there. Then when the install fails, extract the ipa, resign binaries, and copy over to device

**Comment by verygenericname** [comment]
But that's what I do. Maybe other stuff works too

**Comment by lorenzoferron98** [comment]
I don't understand. Do you think that it is possible to install a tweak unzipping DEB and then `scp` its contents into device using a custom patched ramdisk created with your script?

**Comment by verygenericname** [comment]
Yes. It's possible. Are you booting seal-less or something

**Comment by lorenzoferron98** [comment]
So are these commands sufficient and correct
```bash
./sshrd.sh https://updates.cdn-apple.com/2022SummerFCS/fullrestores/012-52718/E165707F-2AA7-40C8-B1A5-0BB94E3F845A/iPhone10,3,iPhone10,6_15.6.1_19G82_Restore.ipsw
```
```bash
./sshrd.sh boot
```
for my purpose?
I don't know if it is required SHSH blob for my purpose. It is correct if I use IPSW for iOS 15.6.1 (currently installed on iPhone X)? Or do I have to use IPSW for iOS 14.6?
