### ISSUE TITLE
init failed

### ISSUE THREAD

**Issue by pwnedcold** [verygenericname/SSHRD_Script#29]
@verygenericname yo im trynna use your tool on a ubuntu based distro but im getting this weird issue

 sudo ./sshrd.sh /home/berti/Downloads/iPhone_4.7_P3_15.6.1_19G82_Restore.ipsw
[sudo] password for berti: 
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000A114A3A3A0026 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: /home/berti/Downloads/iPhone_4.7_P3_15.6.1_19G82_Restore.ipsw
Error init failed
failed

**Comment by verygenericname** [comment]
It has to be a link, not a file, I think you can add file:// behind the filepath and it might work
