### ISSUE TITLE
ios 16 mount failed

### ISSUE THREAD

**Issue by TRANTUAN-PC** [verygenericname/SSHRD_Script#291]
Not bootloop anymore,but failed to mount /mnt2 because of seputil failed to load mnt6/.../sep-firmware.img4
Please,help!

**Comment by imnltsa** [comment]
> seputil failed to load mnt6/.../sep-firmware.img4

https://github.com/verygenericname/SSHRD_Script/issues/279#issuecomment-2131898851

**Comment by TRANTUAN-PC** [comment]
I will close this issue as there is no answer.

**Comment by imnltsa** [comment]
> I will close this issue as there is no answer.

mfw
