### ISSUE TITLE
Can I write **permanently** `/mnt1` with iOS 15?

### ISSUE THREAD

**Issue by lorenzoferron98** [verygenericname/SSHRD_Script#31]
After `mount_filesystems` I created a directory with `mkdir -p /mnt1/usr/lib/frida/` then I used `reboot` command to reboot device in normal mode. Anyway when I runned again `./sshrd.sh boot` to check if directory was present I discovered that it was gone. Why? Maybe because I can't write to `/` in iOS 15?

**Comment by verygenericname** [comment]
No
