### ISSUE TITLE
create ssramdisk fail

### ISSUE THREAD

**Issue by ylcz2014** [verygenericname/SSHRD_Script#33]
OS:ubuntu
iphonex , ios15.1.1
use checkra1n to boot into recovery and dfu

stop at this step for a long time:

chengzi@cheng:~/SSHRD_Script$ sudo ./sshrd.sh https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-63899/6CAB53E5-5411-4140-BA83-0E37B1397558/iPhone10,3,iPhone10,6_15.1_19B74_Restore.ipsw
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000474141032402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000474141032402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SPRAY

**Comment by ylcz2014** [comment]
then stop at this:

ret: false
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000474141032402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000474141032402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SPRAY

**Comment by ylcz2014** [comment]
[](url)

**Comment by verygenericname** [comment]
What processor does your computer hace

**Comment by ylcz2014** [comment]
AMD R7 5800H

**Comment by verygenericname** [comment]
That's why. AMD processors don't treat checkm8 well
