### ISSUE TITLE
Tried to install trollstore on my SE1 ios15.4.1,what is wrong?

### ISSUE THREAD

**Issue by lj4o7** [verygenericname/SSHRD_Script#34]
Terninal1 as:
.......
iOS 15 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1 ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x87000ca6c : 000080d2
applying patch=0x87000ca28 : 000080d2
applying patch=0x870001d28 : 000080d2c0035fd6
applying patch=0x870001d80 : 000080d2c0035fd6
applying patch=0x8700305f0 : 000080d2c0035fd6
applying patch=0x87000e630 : 200080d2
applying patch=0x87000fc50 : 5a930610
applying patch=0x87001ceb8 : 72643d6d64302064656275673d30783230313465202d76207764743d2d312000
applying patch=0x870013708 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8020 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x973ee1
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x106ec64
get_amfi_out_of_my_way_patch: Patching AMFI at 0x106a2a8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
0x106a2a8 0xfd 0xe0
0x106a2a9 0x7b 0x3
0x106a2aa 0xbf 0x0
0x106a2ab 0xa9 0x32
0x106a2ac 0xfd 0xc0
0x106a2ae 0x0 0x5f
0x106a2af 0x91 0xd6
krnl
dtre
rtsc
rdsk
/dev/disk2          	                               	/private/tmp/SSHRD
"disk2" ejected.
none
we are done, please use ./sshrd.sh boot to boot your device
cleanup...
lj407@MacBook-Pro SSHRD_Script % ./sshrd.sh boot
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
device should show text on screen now.
lj407@MacBook-Pro SSHRD_Script % ssh -p2222 root@localhost
The authenticity of host '[localhost]:2222 ([::1]:2222)' can't be established.
ECDSA key fingerprint is SHA256:lb9y8xaKPkXl5gUgA+WHH5TbDlRwWZ6Io7BBLbX+PuE.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
root@localhost's password: 
localhost:~ root# mount_filesystems
seputil: Gigalocker file (/mnt7/09FB8747-67E6-548A-87FE-431C84849C10.gl) exists
seputil: Gigalocker initialization completed
sepi digest (20 bytes): bd669d2359bfbddc0ae2aec6a7018b3de1d32d5c
sepi nonce (20 bytes): 0a8803721c85f286229b26111d69f87d4096c825
rsep digest (20 bytes): 552913c6de9925f4e1e1caf47eefd5cdce2829f5
rsep nonce (20 bytes): 0a8803721c85f286229b26111d69f87d4096c825
localhost:~ root# trollstoreinstaller tips
-sh: trollstoreinstaller: command not found

terminal2 as:

lj407@MacBook-Pro ~ % iproxy 2222 22
Creating listening port 2222 for device port 22
waiting for connection
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 1645 (serial: ramdisk tool Aug 14 2022 11:28:57), port 22

**Comment by verygenericname** [comment]
Clone the repo again

**Comment by lj4o7** [comment]
Problem solved
