### ISSUE TITLE
n71 error

### ISSUE THREAD

**Issue by VR-HoangLong** [verygenericname/SSHRD_Script#35]
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SummerFCS/fullrestores/012-41736/19A1E631-3FB4-4F85-BE5B-266C40FACEEB/iPhone_4.7_15.6_19G71_Restore.ipsw
init done
Error: file Firmware/.trustcache does not exist, or is a directory
failed

**Comment by verygenericname** [comment]
Did you try again. I only have a n71m, and it works for me

**Comment by VR-HoangLong** [comment]
> Did you try again. I only have a n71m, and it works for me

it worked now but i cant ssh into it
─[hoanglong@PainKiller]:[~/SSHRD_Script]
└──╼ $ ssh -p 2222 root@localhost
kex_exchange_identification: read: Connection reset by peer
┌─[hoanglong@PainKiller]:[~/SSHRD_Script]
└──╼ $ ssh -p 4444 root@localhost
kex_exchange_identification: read: Connection reset by peer
┌─[hoanglong@PainKiller]:[~/SSHRD_Script]
└──╼ $

**Comment by itsnebulalol** [comment]
Worked fine on my n71, did you use iproxy?

**Comment by VR-HoangLong** [comment]
> Worked fine on my n71, did you use iproxy?

worked now, but i want to edit com.apple.MobileGestalt.plist
is there any way to do it ?

**Comment by VR-HoangLong** [comment]
when i use nano and save it says operation not permitted

**Comment by verygenericname** [comment]
SEP restrictions

**Comment by HoangLong-Lumi** [comment]
> SEP restrictions

can i create a symlink for this
eg from Downloads
