### ISSUE TITLE
Can't boot ramdisk

### ISSUE THREAD

**Issue by dTolmachev1** [verygenericname/SSHRD_Script#36]
3 and 4 steps from readme complete without errors, but on the device it stops with something like this:
Bootstrap path: path = /AppleInternal/Library/LaunchDaemons, error = 2: No such file or directory.
Hence iProxy also doesn't work: in SSH terminal it says, "connection reset by peer", and in iProxy terminal -- "No connected device found. Terminating"
I'm using LiveUSB with Ubuntu-22.04, installed libimobiledevice-utils, libirecovery-common, libirecovery-1.0-3, irecovery and libusbmuxd-tools as dependences, trying to boot iPhone SE on iOS 15.4.1, as ipsw for step 3 using iOS 15.6.1 (also tried with iOS 15.4.1 link). Before step 3 iPhone successfully paired with PC using "idevicepair pair".

**Comment by verygenericname** [comment]
The phone is fine, its a usbmuxd issue, stop the usbmuxd daemon and compile usbmuxd2 and run that
