### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [verygenericname/SSHRD_Script#37]
Is there some way I can use this on my windows computer? Would I be able to use a linux vm? I just don't have a linux or macos computer, and I want to install trollstore on my ipad.

**Comment by getBoolean** [comment]
I also have a windows machine, so I used two usb drives to get an ubuntu environment running.

Put the ubuntu installer on one and boot into it, then install ubuntu into the other usb drive (make sure not to choose your windows drives). Then boot into the usb drive with the installed ubuntu (not the live ubuntu) and run the script.

Though, im having trouble getting the script to work with my iPad 7 on iPadOS 15.1. I’ll probably need to create an issue for it.

**Comment by verygenericname** [comment]
Use a Live USB
