### ISSUE TITLE
Cannot connect to device - iPad 6th gen

### ISSUE THREAD

**Issue by Manchovies** [verygenericname/SSHRD_Script#41]
![32C943E7-6D82-4CA9-B52B-FD1BB5222914](https://user-images.githubusercontent.com/113330032/189581202-b3087f9c-6c7d-4cef-a4fb-5348f9759986.png)
![F21E7963-1C19-4199-9160-7329D9148281](https://user-images.githubusercontent.com/113330032/189581199-2b1d164a-dc1a-4b32-933e-baae7a8baeea.png)
`Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 005: ID 1ea7:0907 SHARKOON Technologies GmbH Keyboard
Bus 007 Device 004:
ID
046d:0836 Logitech, Inc. B525 HD Webcam
Bus 007 Device 003: ID 1532:0083 Razer USA, Ltd RC30-0315, Gaming Mouse [Basilis
k X HyperSpeed]
Bus 007 Device 002: ID Obda:5411 Realtek Semiconductor Corp. RTS5411 Hub
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 006: ID 264a:1fb4 Thermaltake
Bus 003 Device 005: ID 0424:2512 Microchip Technology, Inc. (formerly SMSC) USB
2.0 Hub
Bus 003 Device 004: ID 1e71:2007 NZXT NZXT USB Device
Bus 003 Device 003:
ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 003 Device 002: ID 1462:7c37 Micro Star International MYSTIC LIGHT
Bus 003 Device 020: ID 05ac:1227 Apple, Inc. Mobile Device (FU Mode)
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001:
ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 8087:0aa7 Intel Corp. Wireless-AC 3168 Bluetooth
Bus 001 Device 002: ID 1532:0083 Razer USA, Ltd RC30-0315, Gaming Mouse [Basilis
k X HyperSpeed]
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub `

I keep running into an error saying it can’t connect to the device. I checked the only place I know (I’m n00b) and it looks like the device is connected, in DFU mode, and has the right device ID(?), but I keep running into this error in the screenshot. iPad 6th Gen cellular, 15.4. I have libusb installed and am running the latest release of Ubuntu, freshly installed.

**Comment by Manchovies** [comment]
Okay, ran the same command with sudo and it worked, but now it’s getting stuck at
“Found the USB handle.
Stage: SPRAY”

And never goes anywhere. Thanks!

**Comment by MikeTheDead** [comment]
You dont understand how much this helped me. My mouse getting unplugged and plugged back in worked too

**Comment by Manchovies** [comment]
That’s awesome!!! I thought it was so weird, there’s no way anyone else would have the same problem :D I hope this is useful to the dev and more.

**Comment by verygenericname** [comment]
run it with sudo
