### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by DarkZone-World** [verygenericname/SSHRD_Script#42]
When i run the script it shows this:
./sshrd.sh: 43: ./sshrd.sh: Linux/irecovery: Exec format error
./sshrd.sh: 44: ./sshrd.sh: Linux/irecovery: Exec format error
./sshrd.sh: 133: ./sshrd.sh: Linux/gaster: Exec format error
failed

What's wrong?

**Comment by Cowboy-Shuai** [comment]
How to solve it？

**Comment by Selt3r** [comment]
I need it too
