### ISSUE TITLE
Failure to use boot command

### ISSUE THREAD

**Issue by ShatteredDisk** [verygenericname/SSHRD_Script#43]
Note: coming from TrollStore install methods

From Issue #40:
>I just tried it again without running ./sshrd.sh boot afterwards and it turned itself on after a few seconds. It seems to be turning itself on before ./sshrd.sh boot can run/finish.

This also seems to be the case for me; The boot command has been run many times and has always caused the device to restart right after the second loading bar reaches 100%.

The initial command seems to run fine but cannot boot the device without "./sshrd.sh boot", which restarts the target device before it itself can finish the boot process.

One thing of note is that the first time I used this script it worked fine without problems, but I already had an Xcode test app by the same name of "TrollInstaller", so I assume it blocked the new one from installing.

Info: iPad 6,11 / Gen 5 WiFi / iOS 15.1 / A9 architecture

**Comment by verygenericname** [comment]
Try like 14.3 ipsw, that worked for someone else

**Comment by ShatteredDisk** [comment]
I’ll try tonight and get back to you

**Comment by ShatteredDisk** [comment]
I just tried it again with an ipsw from 14.3 and it just failed and booted the device after the _first_ loading bar reached 100%.

Output:
`SSHRD_Script % ./sshrd.sh boot
[==================================================] 100.0%
ERROR: Unable to connect to device
failed
`

**Comment by verygenericname** [comment]
What phone is this? How are you entering DFU? Does it restart randomly in DFU?

**Comment by ShatteredDisk** [comment]
I am using an iPad (5th Gen WiFi / 6,11) running iOS 15.1.
I entered DFU mode by:
-holding the home and power button at the same time for ~3 seconds until the screen darkens slightly
-releasing the power button
-holding the home button until the script detects dfu and continues
-releasing the home button

It does not restart randomly in DFU mode. It only restarts after being either triggered by some step in between each loading bar, or when the power cable is disconnected.

**Comment by verygenericname** [comment]
Weird. My iphone 6s plus works fine which has the same processor

**Comment by ShatteredDisk** [comment]
Is there anything else I should try?

**Comment by Dialgatrainer02** [comment]
i get the same error with iphone 8 on 15.5b4
