### ISSUE TITLE
Error when installing TrollStore via this script

### ISSUE THREAD

**Issue by afastaudir8** [verygenericname/SSHRD_Script#55]
I'm getting an error when installing the app with the script.

```
[*] Getting device info... this may take a second
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9
[-] An error occurred

```

The command I'm running is `sudo ./sshrd.sh 15.4.1 TrollStore Tips`
I'm installing it onto iOS 15.5 Beta 4 on my iPhone 8 (10,4)
I'm using Linux Mint 20.3

**Comment by verygenericname** [comment]
You need a newer version of linux mint, need to statically link PlistBuddy
