### ISSUE TITLE
ios 16 mount issue iphone 8

### ISSUE THREAD

**Issue by ranzhie07** [verygenericname/SSHRD_Script#59]
ssh is okay and when im trying to mount_filesystems iget this error
![image](https://user-images.githubusercontent.com/13744581/191101691-01359331-c3ef-4a52-bb71-5d407f2360c7.png)

**Comment by verygenericname** [comment]
Need to fix that, will be fixed soon

**Comment by ranzhie07** [comment]
> Need to fix that, will be fixed soon

Bro can i manually mount the partition for ios16 iphone 8?

**Comment by verygenericname** [comment]
disk0s1s1 is disk1s1 on ios 16

**Comment by ranzhie07** [comment]
> disk0s1s1 is disk1s1 on ios 16

Thanks brother i figured it out with your help I created a universal mounting :) ![image](https://user-images.githubusercontent.com/13744581/191144861-bbd258cb-fadb-48a2-be76-973869d800bf.jpeg)

**Comment by ranzhie07** [comment]
> > disk0s1s1 is disk1s1 on ios 16
> 
> Thanks brother i figured it out with your help I created a universal mounting :) ![image](https://user-images.githubusercontent.com/13744581/191144861-bbd258cb-fadb-48a2-be76-973869d800bf.jpeg)

It's working my bro universal_mounting tested on ios 15 and 16 ip7 and ip8 ![image](https://user-images.githubusercontent.com/13744581/191146890-5cd0a6b2-02a0-4c3f-bc7e-da5cfc935751.jpeg)

**Comment by turboxxxp** [comment]
please add universal_mounting test ios 16
