### ISSUE TITLE
need to access via sftp protocol

### ISSUE THREAD

**Issue by jerry-maheswara-github** [verygenericname/SSHRD_Script#6]
Dear [Nathan](https://github.com/verygenericname),

please put /usr/lib/libresolv.9.dylib in ssh.tar so that we can access via sftp protocol.

I did it in my experiment, and it worked.

Thanks.

**Comment by verygenericname** [comment]
will add

**Comment by verygenericname** [comment]
i think i fixed the issue by compiling the dylib from scratch from this github repo i found: https://github.com/aosm/libresolv

**Comment by verygenericname** [comment]
fix pushed

**Comment by jerry-maheswara-github** [comment]
Great!
