### ISSUE TITLE
Failure to mount partition using mount_filesystems

### ISSUE THREAD

**Issue by ranzhie07** [verygenericname/SSHRD_Script#60]
Can i mount manually the partition? This happens when trying to mount_filesystems for A11 device iOS16 , iPhone10,1 , iPhone 8.

What will be the mounting syntax for manual mounting? Thanks in advance for your help

![image](https://user-images.githubusercontent.com/13744581/191133219-0b799101-1bae-4305-8aad-c140a5485add.png)

**Comment by verygenericname** [comment]
iOS 16 renamed the disk numbers. I need to edit my mount_filesystems script to accommodate for that.
