### ISSUE TITLE
Failed to mount on renci ssh but on manual terminal okay

### ISSUE THREAD

**Issue by ranzhie07** [verygenericname/SSHRD_Script#61]
Im doing .net but when i try to call mount on renci ssh i got error but when i try manually on cmd mount success do you have any idea of this bro?![image](https://user-images.githubusercontent.com/13744581/191236479-cf08706e-0305-4fb3-840e-20c0305afb07.jpeg)

**Comment by verygenericname** [comment]
Maybe use built-in ssh on windows 10-11? Or putty?

**Comment by ranzhie07** [comment]
> Maybe use built-in ssh on windows 10-11? Or putty?

Seputil error no such process 😅

**Comment by verygenericname** [comment]
That always appears, that's normal

**Comment by ranzhie07** [comment]
> Maybe use built-in ssh on windows 10-11? Or putty?

I can't authenticate when running single command

**Comment by ranzhie07** [comment]
> Maybe use built-in ssh on windows 10-11? Or putty?

Same result in putty when running on commandline 😭

**Comment by ranzhie07** [comment]
> Maybe use built-in ssh on windows 10-11? Or putty?

I think i knew the problem bro what is the path of mount_apfs?

**Comment by erotics1** [comment]
i have same problem on mac and windows ... mount apfs automatic failed

**Comment by erotics1** [comment]
> That always appears, that's normal

create auto mount command please

**Comment by verygenericname** [comment]
It looks like it mounted fine judging on the verbose

**Comment by verygenericname** [comment]
fixed
