### ISSUE TITLE
arm64 Darwin binaries?

### ISSUE THREAD

**Issue by badger200** [verygenericname/SSHRD_Script#63]
Any possibility of getting arm64 binaries? Or where is the source I can compile myself?

The truth is I want to run this on my iPad Pro A12X via Apple USB-C to Lightning cable to my guest iPad Pro A9X. I have successfully modified libimobiledevice with IOKit entitlements that allowed me to issue irecovery commands to my A9X iPad Pro (read / change boot args.) and now this would be slick as hell if I can do it without needing a PC at all.

But this would apply to people running M1 Macs arm64 too.

**Comment by verygenericname** [comment]
I actually tried this on my iPad Air 2! I got it running, but it’s too much work, and I did NOT expect someone else to try it lol

**Comment by badger200** [comment]
@verygenericname Why was this closed as completed? There still aren't any arm64 binaries. Only x86-64.
