### ISSUE TITLE
mount_filesystems  mount_apfs: command not found

### ISSUE THREAD

**Issue by erotics1** [verygenericname/SSHRD_Script#64]
sshpass -p alpine ssh -o StrictHostKeyChecking=no root@localhost -p 2222 mount_filesystems > /dev/null

/usr/bin/mount_filesystems: line 1: mount_apfs: command not found
/usr/bin/mount_filesystems: line 16: mount_apfs: command not found
/usr/bin/mount_filesystems: line 34: mount_apfs: command not found
seputil.c: Gigalocker initialization failed: 30
seputil: can't open '/mnt1/usr/standalone/firmware/sep-firmware.img4', errno: No such file or directory(2)
seputil: rejecting zero-byte firmware
seputil: failed to load /mnt1/usr/standalone/firmware/sep-firmware.img4 in  mode
/usr/bin/mount_filesystems: line 53: mount_apfs: command not found

**Comment by verygenericname** [comment]
ill fix that

**Comment by verygenericname** [comment]
what ios version btw

**Comment by erotics1** [comment]
iOS 15.6.1

**Comment by erotics1** [comment]
You should create an auto mount or be able to fix it with the command sshpass -p alpine ssh -o StrictHostKeyChecking=no root@localhost -p 2222 mount_filesystems > /dev/null

**Comment by erotics1** [comment]
and you could check in iOS 16 the paths for the mount as well thanks to very work

**Comment by erotics1** [comment]
![image](https://user-images.githubusercontent.com/38079079/191884149-b11fe2b7-d8a2-4dfa-bc00-e8b77485e349.png)
Same problem

**Comment by verygenericname** [comment]
fixing right now
