### ISSUE TITLE
Recieving error when doing ./sshrd.sh 14.7.1 

### ISSUE THREAD

**Issue by zqkii** [verygenericname/SSHRD_Script#66]
ERROR: Unable to connect to device
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

IPad Pro Gen 1 10.5 inch. IOS 14.7.

**Comment by verygenericname** [comment]
is the device in dfu, are you on linux, if so, run it with sudo

**Comment by zqkii** [comment]
Sorry i am new to linux, 

How do I run the command with sudo?

**Comment by verygenericname** [comment]
sudo ./sshrd.sh 14.7.1
