### ISSUE TITLE
Error init failed 

### ISSUE THREAD

**Issue by amats211** [verygenericname/SSHRD_Script#69]
Was behind latest commit so i did a git pull..

And when i try to run sshrd.sh after, it shows error..

[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: null
Error init failed
[-] An error occurred

It was working well before making a pull

i am using a mac with catalina os

**Comment by itsnebulalol** [comment]
Show the command you're using

**Comment by amats211** [comment]
sure, here is complete logs..

Macs-MacBook-Pro:SSHRD_Script mac$ ./sshrd.sh https://updates.cdn-apple.com/2022SummerSeed/fullrestores/012-71295/B50C5388-3998-48DA-A6E5-57E903F8B719/iPhone10,3,iPhone10,6_16.1_20B5050f_Restore.ipsw
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: null
Error init failed
[-] An error occurred

**Comment by itsnebulalol** [comment]
The command should be `./sshrd.sh 14.8`

We switched to using just the version number, not the ipsw. 14.8 is recommended, obviously you can choose whatever

**Comment by amats211** [comment]
hmm ok, using that command fixed it, thanks.  but why is 16 and 16.1 generating error now? before i pulled i was able to make ios16 for device well

**Comment by itsnebulalol** [comment]
16.0 should work, 16.1 not since its a beta

**Comment by amats211** [comment]
hmm, ok... will wait for update then. I will close this issue as it is solved. thank you very much

**Comment by ranzhie07** [comment]
Bro theres an issue with mount in ipx ios16.0
Boot ok
Ssh connect
Mount failed see error it rebooted the ssh

**Comment by itsnebulalol** [comment]
You should use 14.8 for the ramdisk version
