### ISSUE TITLE
Iphone x issue on mounting

### ISSUE THREAD

**Issue by ranzhie07** [verygenericname/SSHRD_Script#73]
Boot ok 
Ssh ok
Mount failed causing ssh access gone
![image](https://user-images.githubusercontent.com/13744581/192096804-35a44d8b-90ef-4e68-9762-d9dd1e29eeaa.jpeg)

**Comment by verygenericname** [comment]
Gonna make the mount_filesystems script auto do it, those commands helped, thanks

**Comment by ranzhie07** [comment]
> Gonna make the mount_filesystems script auto do it, those commands helped, thanks

Bro mounting procedure is correct but the problem is when mounting /mnt2 it hangs in like 1min and ssh access will be gone this only happen in ipx what is the problem? On ip8 its okay

**Comment by ranzhie07** [comment]
> Gonna make the mount_filesystems script auto do it, those commands helped, thanks
use this code bro for universal

function get_path {
	for disk_path in /dev/disk*; do
		if [[ $(/System/Library/Filesystems/apfs.fs/apfs.util -p $disk_path) == "$1" ]]; then
			echo $disk_path
			break
		fi
	done
}

system_path=$(get_path "System")
/sbin/mount_apfs $system_path /mnt1

system_path=$(get_path "Preboot")
/sbin/mount_apfs $system_path /mnt6

system_path=$(get_path "xART")
/sbin/mount_apfs $system_path /mnt7
/usr/libexec/seputil --gigalocker-init

if [[ -e /mnt6/active ]]; then
/usr/libexec/seputil --load /mnt6/$(cat /mnt6/active)/usr/standalone/firmware/sep-firmware.img4
else
/usr/libexec/seputil --load /mnt1/usr/standalone/firmware/sep-firmware.img4
fi

system_path=$(get_path "Data")
/sbin/mount_apfs $system_path /mnt2

**Comment by verygenericname** [comment]
fixed
