### ISSUE TITLE
iOS 16 

### ISSUE THREAD

**Issue by erotics1** [verygenericname/SSHRD_Script#75]

**Comment by erotics1** [comment]
mount_apfs: volume could not be mounted: No such file or directory
AssertMacros:(value = 0x0),  file: seputil.c, line: 2783
seputil: can't open '/mnt1/usr/standalone/firmware/sep-firmware.img4', errno: No such file or directory(2)
seputil.c: failed to load /mnt1/usr/standalone/firmware/sep-firmware.img4 in  mode
mount_apfs: volume could not be mounted: No such file or directory

**Comment by verygenericname** [comment]
can you run ls /dev/disk*

**Comment by verygenericname** [comment]
pinned potential mountinmg issuer
