### ISSUE TITLE
Can't make ramdisk iPhone 5s iOS 7.1

### ISSUE THREAD

**Issue by ooglecg** [verygenericname/SSHRD_Script#76]
When I run `./sshrd.sh 7.1` I get this error. `christos@Christoss-Mac-Mini SSHRD_Script % ./sshrd.sh 7.1
Archive:  gaster-Darwin.zip
  inflating: gaster                  
[*] Waiting for device in DFU mode
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/iOS7.1/031-4452.20140310.Lv4Gr/iPhone6,2_7.1_11D167_Restore.ipsw
init done
getting: BuildManifest.plist
  0% [                                                                          100% [========================================================================== 45% [============================================>                              91% [==========================================================================100% [===================================================================================================>]
download succeeded
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/iOS7.1/031-4452.20140310.Lv4Gr/iPhone6,2_7.1_11D167_Restore.ipsw
init done
getting: Firmware/dfu/iBSS.n53ap.RELEASE.im4p
  0% [                                                                          100% [==========================================================================  0% [                                                                            1% [>                                                                           3% [==>                                                                         5% [====>                                                                       6% [=====>                                                                      6% [=====>                                                                      7% [======>                                                                     8% [=======>                                                                   10% [=========>                                                                 11% [==========>                                                                12% [===========>                                                               14% [=============>                                                             16% [===============>                                                           17% [================>                                                          18% [=================>                                                         19% [==================>                                                        20% [===================>                                                       21% [====================>                                                      22% [=====================>                                                     23% [======================>                                                    26% [=========================>                                                 26% [=========================>                                                 27% [==========================>                                                31% [==============================>                                            34% [=================================>                                         35% [==================================>                                        38% [=====================================>                                     40% [=======================================>                                   42% [=========================================>                                 44% [===========================================>                               45% [============================================>                              47% [==============================================>                            49% [================================================>                          50% [=================================================>                         52% [===================================================>                       53% [====================================================>                      55% [======================================================>                    58% [=========================================================>                 58% [=========================================================>                 59% [==========================================================>                62% [=============================================================>             63% [==============================================================>            64% [===============================================================>           64% [===============================================================>           68% [===================================================================>       71% [======================================================================>    72% [=======================================================================>   73% [========================================================================>  76% [========================================================================== 77% [========================================================================== 78% [========================================================================== 79% [========================================================================== 82% [========================================================================== 84% [========================================================================== 84% [========================================================================== 84% [========================================================================== 85% [========================================================================== 86% [========================================================================== 87% [========================================================================== 89% [========================================================================== 90% [========================================================================== 90% [========================================================================== 90% [========================================================================== 96% [========================================================================== 96% [========================================================================== 97% [==========================================================================100% [===================================================================================================>]
download succeeded
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/iOS7.1/031-4452.20140310.Lv4Gr/iPhone6,2_7.1_11D167_Restore.ipsw
init done
getting: Firmware/dfu/iBEC.n53ap.RELEASE.im4p
  0% [                                                                          100% [==========================================================================  0% [                                                                            0% [                                                                            1% [>                                                                           1% [>                                                                           1% [>                                                                           2% [=>                                                                          2% [=>                                                                          2% [=>                                                                          3% [==>                                                                         4% [===>                                                                        4% [===>                                                                        5% [====>                                                                       5% [====>                                                                       5% [====>                                                                       6% [=====>                                                                      6% [=====>                                                                      6% [=====>                                                                      6% [=====>                                                                      7% [======>                                                                     8% [=======>                                                                    8% [=======>                                                                    8% [=======>                                                                    8% [=======>                                                                    9% [========>                                                                   9% [========>                                                                  10% [=========>                                                                 10% [=========>                                                                 11% [==========>                                                                11% [==========>                                                                12% [===========>                                                               12% [===========>                                                               12% [===========>                                                               13% [============>                                                              13% [============>                                                              13% [============>                                                              14% [=============>                                                             15% [==============>                                                            15% [==============>                                                            16% [===============>                                                           16% [===============>                                                           17% [================>                                                          17% [================>                                                          17% [================>                                                          18% [=================>                                                         18% [=================>                                                         19% [==================>                                                        19% [==================>                                                        19% [==================>                                                        20% [===================>                                                       20% [===================>                                                       20% [===================>                                                       21% [====================>                                                      21% [====================>                                                      21% [====================>                                                      22% [=====================>                                                     23% [======================>                                                    23% [======================>                                                    23% [======================>                                                    24% [=======================>                                                   24% [=======================>                                                   24% [=======================>                                                   25% [========================>                                                  26% [=========================>                                                 26% [=========================>                                                 27% [==========================>                                                27% [==========================>                                                28% [===========================>                                               28% [===========================>                                               28% [===========================>                                               28% [===========================>                                               29% [============================>                                              30% [=============================>                                             30% [=============================>                                             30% [=============================>                                             31% [==============================>                                            31% [==============================>                                            31% [==============================>                                            32% [===============================>                                           32% [===============================>                                           32% [===============================>                                           33% [================================>                                          33% [================================>                                          34% [=================================>                                         34% [=================================>                                         34% [=================================>                                         35% [==================================>                                        35% [==================================>                                        35% [==================================>                                        36% [===================================>                                       36% [===================================>                                       37% [====================================>                                      37% [====================================>                                      37% [====================================>                                      38% [=====================================>                                     38% [=====================================>                                     39% [======================================>                                    39% [======================================>                                    40% [=======================================>                                   40% [=======================================>                                   41% [========================================>                                  42% [=========================================>                                 42% [=========================================>                                 42% [=========================================>                                 42% [=========================================>                                 43% [==========================================>                                43% [==========================================>                                44% [===========================================>                               44% [===========================================>                               45% [============================================>                              45% [============================================>                              45% [============================================>                              46% [=============================================>                             46% [=============================================>                             46% [=============================================>                             47% [==============================================>                            48% [===============================================>                           48% [===============================================>                           49% [================================================>                          49% [================================================>                          49% [================================================>                          50% [=================================================>                         50% [=================================================>                         50% [=================================================>                         51% [==================================================>                        51% [==================================================>                        51% [==================================================>                        52% [===================================================>                       52% [===================================================>                       53% [====================================================>                      53% [====================================================>                      54% [=====================================================>                     54% [=====================================================>                     54% [=====================================================>                     55% [======================================================>                    55% [======================================================>                    56% [=======================================================>                   56% [=======================================================>                   57% [========================================================>                  57% [========================================================>                  58% [=========================================================>                 58% [=========================================================>                 58% [=========================================================>                 59% [==========================================================>                60% [===========================================================>               60% [===========================================================>               61% [============================================================>              61% [============================================================>              61% [============================================================>              62% [=============================================================>             62% [=============================================================>             63% [==============================================================>            64% [===============================================================>           64% [===============================================================>           64% [===============================================================>           65% [================================================================>          66% [=================================================================>         66% [=================================================================>         66% [=================================================================>         67% [==================================================================>        68% [===================================================================>       68% [===================================================================>       69% [====================================================================>      69% [====================================================================>      69% [====================================================================>      70% [=====================================================================>     70% [=====================================================================>     71% [======================================================================>    71% [======================================================================>    72% [=======================================================================>   72% [=======================================================================>   72% [=======================================================================>   73% [========================================================================>  74% [=========================================================================> 74% [=========================================================================> 75% [========================================================================== 76% [========================================================================== 76% [========================================================================== 77% [========================================================================== 78% [========================================================================== 78% [========================================================================== 79% [========================================================================== 79% [========================================================================== 80% [========================================================================== 80% [========================================================================== 80% [========================================================================== 80% [========================================================================== 81% [========================================================================== 82% [========================================================================== 83% [========================================================================== 83% [========================================================================== 84% [========================================================================== 84% [========================================================================== 84% [========================================================================== 85% [========================================================================== 85% [========================================================================== 85% [========================================================================== 86% [========================================================================== 86% [========================================================================== 87% [========================================================================== 88% [========================================================================== 88% [========================================================================== 88% [========================================================================== 89% [========================================================================== 89% [========================================================================== 90% [========================================================================== 90% [========================================================================== 91% [========================================================================== 91% [========================================================================== 92% [========================================================================== 93% [========================================================================== 93% [========================================================================== 94% [========================================================================== 94% [========================================================================== 94% [========================================================================== 94% [========================================================================== 95% [========================================================================== 95% [========================================================================== 96% [========================================================================== 96% [========================================================================== 97% [========================================================================== 97% [========================================================================== 98% [========================================================================== 98% [========================================================================== 99% [========================================================================== 99% [==========================================================================100% [===================================================================================================>]
download succeeded
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/iOS7.1/031-4452.20140310.Lv4Gr/iPhone6,2_7.1_11D167_Restore.ipsw
init done
getting: Firmware/all_flash/all_flash.n53ap.production/DeviceTree.n53ap.im4p
  0% [                                                                          100% [==========================================================================  1% [>                                                                           3% [==>                                                                         5% [====>                                                                       6% [=====>                                                                      7% [======>                                                                     9% [========>                                                                  10% [=========>                                                                 11% [==========>                                                                12% [===========>                                                               14% [=============>                                                             15% [==============>                                                            16% [===============>                                                           17% [================>                                                          19% [==================>                                                        21% [====================>                                                      22% [=====================>                                                     23% [======================>                                                    24% [=======================>                                                   26% [=========================>                                                 27% [==========================>                                                28% [===========================>                                               30% [=============================>                                             32% [===============================>                                           33% [================================>                                          35% [==================================>                                        36% [===================================>                                       39% [======================================>                                    40% [=======================================>                                   41% [========================================>                                  44% [===========================================>                               45% [============================================>                              46% [=============================================>                             49% [================================================>                          50% [=================================================>                         50% [=================================================>                         51% [==================================================>                        53% [====================================================>                      54% [=====================================================>                     56% [=======================================================>                   56% [=======================================================>                   59% [==========================================================>                61% [============================================================>              62% [=============================================================>             63% [==============================================================>            64% [===============================================================>           67% [==================================================================>        68% [===================================================================>       69% [====================================================================>      71% [======================================================================>    72% [=======================================================================>   73% [========================================================================>  75% [========================================================================== 76% [========================================================================== 78% [========================================================================== 80% [========================================================================== 82% [========================================================================== 83% [========================================================================== 84% [========================================================================== 85% [========================================================================== 88% [========================================================================== 89% [========================================================================== 92% [========================================================================== 95% [========================================================================== 95% [========================================================================== 96% [========================================================================== 98% [========================================================================== 99% [==========================================================================100% [===================================================================================================>]
download succeeded
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/iOS7.1/031-4452.20140310.Lv4Gr/iPhone6,2_7.1_11D167_Restore.ipsw
init done
Error: file Firmware/058-4345-002.dmg.trustcache does not exist, or is a directory
[-] An error occurred
[-] uploading logs, if this fails, it's not a big deal.
ls: *.log: No such file or directory
curl: (26) Failed to open/read local data from file/application`

**Comment by verygenericname** [comment]
im sorry dude, but this only supports 12+, im assuming you are trying to remove passcode?

**Comment by verygenericname** [comment]
because i removed passcode from my 7.1.2 5s

**Comment by ooglecg** [comment]
> im sorry dude, but this only supports 12+, im assuming you are trying to remove passcode?

Nope I'm trying to save SHSH blobs.

**Comment by verygenericname** [comment]
in that case, just use the latest ios 12 version, doesn't matter

**Comment by ooglecg** [comment]
> in that case, just use the latest ios 12 version, doesn't matter

Wait, so what commands do I need to use then? I'm not an expert but I'm pretty sure i cant skip the command I used in the post?

**Comment by verygenericname** [comment]
./sshrd.sh 12.5.7

**Comment by ooglecg** [comment]
> ./sshrd.sh 12.5.7

Ok thanks
