### ISSUE TITLE
boot-args too long, which may cause patches not work

### ISSUE THREAD

**Issue by Halo-Michael** [verygenericname/SSHRD_Script#77]
Boot args string can't be too long, it may cause patches not work. In my test, the origin version doesn't work on A10, iOS15.4.1 (but do work on A10, iOS15.1). so I removed a boot arg "debug=0x2014e", everything works fine again.

**Comment by verygenericname** [comment]
huh, that's weird, it works fine for me on my touch 7

**Comment by Halo-Michael** [comment]
> huh, that's weird, it works fine for me on my touch 7

I'm using iPhone7(iPhone9,1 d10ap)

**Comment by verygenericname** [comment]
i know, they share the same processor

**Comment by verygenericname** [comment]
wdt is to disable the watchdog timer so it doesnt randomly panic, debug just enables some more stuff
