### ISSUE TITLE
IPHONE X SSH COLLAPSE AFTER MOUNT

### ISSUE THREAD

**Issue by ranzhie07** [verygenericname/SSHRD_Script#78]
Same issue after mounting filesystems it hangs like about 1min and the ssh will disconnect it happens only in ipx i tried two ipx same problem.
Please look in image below this occurs after mount_filesystems for ipx other unit no problem
![image](https://user-images.githubusercontent.com/13744581/192122606-de80c400-2448-4f23-8c44-af2c75da165b.jpeg)

**Comment by verygenericname** [comment]
make sure you use a relatively close version to the version the phone is running

**Comment by itsnebulalol** [comment]
IPHONE X SSH COLLAPSE AFTER MOUNT

**Comment by ranzhie07** [comment]
> make sure you use a relatively close version to the version the phone is running

Yes bro ipx is ios16.0 and the ramdisk loaded is also ios16.0

**Comment by ranzhie07** [comment]
What seams to be the issue bro ipx is ios16 and i loaded ramdisk of ios 16 also same but it hangs in mounting the /mnt2/

**Comment by ranzhie07** [comment]
> make sure you use a relatively close version to the version the phone is running

What seams to be the issue bro ipx is ios16 and i loaded ramdisk of ios 16 also same but it hangs in mounting the /mnt2/
Its a weird problem because it is okay with ip8 only ipx had this problem tried 4 ipx same issue

**Comment by itsnebulalol** [comment]
Try 14.8 as the ramdisk version

**Comment by ranzhie07** [comment]
> Try 14.8 as the ramdisk version

even if the ios of device is ios16?

**Comment by ranzhie07** [comment]
> make sure you use a relatively close version to the version the phone is running

if iphone 6 ios 16 heres the problem mount hangs and closing the ssh see photo below it not showing verbose
![image](https://user-images.githubusercontent.com/13744581/192155003-a1580437-8198-4b50-ab83-74440363a760.png)

**Comment by yunxuan0530** [comment]
Have you solved it yet?

**Comment by yunxuan0530** [comment]
Is it the kernel problem?

**Comment by itsnebulalol** [comment]
> even if the ios of device is ios16?

Yes

> if iphone x ios 16 heres the problem mount hangs and closing the ssh see photo below it not showing verbose do you think restored_external has to do with it?

Seems like it isn’t respecting the -v bootarg, and isn’t booting properly. Might be a 16 host thing

**Comment by ranzhie07** [comment]
> > even if the ios of device is ios16?
> 
> 
> 
> Yes
> 
> 
> 
> > if iphone x ios 16 heres the problem mount hangs and closing the ssh see photo below it not showing verbose do you think restored_external has to do with it?
> 
> 
> 
> Seems like it isn’t respecting the -v bootarg, and isn’t booting properly. Might be a 16 host thing

Tried 14.8 but still same problem

**Comment by Asm0d3usX** [comment]
Anyone have solution for this problem ?

**Comment by verygenericname** [comment]
Not sure why it happens

**Comment by erotics1** [comment]
> Anyone have solution for this problem ?

Send me you telegram i have solution i am sethos

**Comment by Asm0d3usX** [comment]
> > Anyone have solution for this problem ?
> 
> Send me you telegram i have solution i am sethos

Contact me here
https://t.me/Asm0d3usX

**Comment by azouzen** [comment]
Anyone have solution for this problem ?

**Comment by azouzen** [comment]
Mounted with same iOS iPhone X iOS 16.0.2 same problem ssh close 
seputil: Gigalocker file (/mnt7/6BC41069-F8A3-5177-9276-93881CE0E9A5.gl) exists
seputil: Gigalocker initialization completed
Connection to localhost closed by remote host.
Connection to localhost closed.

**Comment by azouzen** [comment]
./sshrd.sh 16.0.2

**Comment by jacquesTech** [comment]
TO MOUNT MN2 YOU NEED FIRST PATH THE SEPFIRMWARE AND MOUNT XART AND THE PREBOOT SYSTEM FILMS  IF YOU NEED THE MOUNT CODE IOS16 JUST COME HERE : https://t.me/gsmadjaasupport/

**Comment by CE1CECL** [comment]
> 

I have the same issue on IPad6,11 and it kernel panics when I run mount command, I use palera1n SSH, but nobody responded in discord. I also tried the sketchy telegram group above and, well, see the images attached. It might be a scam? (Asking for remote Connection without reason) 
![Screenshot_20230108-164403](https://user-images.githubusercontent.com/52040854/211220744-e8c50112-d3a8-4b92-b7fd-157ad0b1f199.png)
![Screenshot_20230108-164400](https://user-images.githubusercontent.com/52040854/211220745-e4a34b2b-3c8d-4bef-a218-05302c2eba90.png)
![Screenshot_20230108-164352](https://user-images.githubusercontent.com/52040854/211220747-ea29e2d2-6d4d-4b58-a48f-45d6d89e74a4.png)
![Screenshot_20230108-164345](https://user-images.githubusercontent.com/52040854/211220748-5e2b42c1-6ea3-423f-ad9e-0e0e39c9c7d9.png)
![Screenshot_20230108-164335](https://user-images.githubusercontent.com/52040854/211220749-44d450f0-e90b-4c13-bafc-473e6185caa5.png)
![Screenshot_20230108-164332](https://user-images.githubusercontent.com/52040854/211220750-71384786-4623-4d3c-b861-4e45741fd884.png)
![Screenshot_20230108-164326](https://user-images.githubusercontent.com/52040854/211220751-053e58b0-49a8-43ac-a1c5-6bb9a2074b16.png)
![Screenshot_20230108-164323](https://user-images.githubusercontent.com/52040854/211220752-844ec27e-693c-4370-b18f-f23959d6940b.png)
![IMG_20230108_163952](https://user-images.githubusercontent.com/52040854/211220754-5d099cb2-8b47-4e71-9d5c-fd25c3941fd6.jpg)

They don't even seem to speak English but in all caps, might be a red flag for you @verygenericname

**Comment by verygenericname** [comment]
fixed with palesshrd branch. only works on macos though

**Comment by jacquesTech** [comment]
GUYS I AM SELLING RAMDISK 16.4+ NO BOOTLOOP IPADS & IPHONES  + MOUNT .DON T  COME ASK FOR FREE 
HERE IS MY TELEGRAM ACCOUNT : https://t.me/gsmadjaa05/   . Thanks

**Comment by Asm0d3usX** [comment]
I give a free guys ramdisk 16.4+ no bootloop ipad and iphone no need buy for ramdisk file guys

**Comment by Helloyunho** [comment]
> fixed with palesshrd branch. only works on macos though

@verygenericname so I tried using that branch and it booted, but it keeps telling me that apfs is failing to do 'mountroot'

**Comment by TRANTUAN-PC** [comment]
Already fixed that problem.

**Comment by lord-Tito** [comment]
> Already fixed that problem with self-research.Thanks to verygenericname and his staff for the great contribution to the community.Thank You.

Hi there… am still facing this problem I can mount iPhone8s and iPads but iPhone X just won’t.. any help would be highly appreciated

**Comment by He5929** [comment]
> 我给你们免费提供一个 ramdisk 16.4+ 没有 bootloop ipad 和 iphone 不需要购买 ramdisk 文件

How can I contact you

**Comment by egor835** [comment]
> I used [my fork of your fork of palera1n](https://github.com/Helloyunho/palera1n)(yes lol), which I edited the MakeFile to change the expired pongo/checkra1n links to the new one

@Helloyunho if you stiil have compiled palera1n binary, could you you please send it here? I can't compile it, I get an error in optparse.c (228:16: variable has incomplete type 'struct stat')

**Comment by Helloyunho** [comment]
> > I used [my fork of your fork of palera1n](https://github.com/Helloyunho/palera1n)(yes lol), which I edited the MakeFile to change the expired pongo/checkra1n links to the new one
> 
> [@Helloyunho](https://github.com/Helloyunho) if you stiil have compiled palera1n binary, could you you please send it here? I can't compile it, I get an error in optparse.c (228:16: variable has incomplete type 'struct stat')

sorry, i don't have it anymore

**Comment by CE1CECL** [comment]
Have you tried to re-run the action? I'll see if I can get it working in a little.

**Comment by CE1CECL** [comment]
[verygenericname-palera1n.patch](https://github.com/user-attachments/files/24474071/verygenericname-palera1n.patch)
This is all the `verygenericname` `palera1n` fork seems to do:
- `.github/workflows/build.yml`: Changed to upload finished binaries to GitHub instead of the palera1n's internal server of whatever
- `src/Makefile`: The `Helloyunho` fork reverted this, but it would use some special build of `Pongo.bin` & `checkra1n-kpf-pongo`?
- `src/pongo_helper.c`: This is where the real changes come in you should apply to the latest palera1n for the ramdisk stuff (if it still merges anyways)
