### ISSUE TITLE
iPhoneX IOS16.0.2 Boot16.0

### ISSUE THREAD

**Issue by yunxuan0530** [verygenericname/SSHRD_Script#81]
![image](https://user-images.githubusercontent.com/43806736/192151898-4b0d8da4-a297-4c6c-8e9b-c397cb9521da.png)

**Comment by verygenericname** [comment]
Yeah i don't know why ios 16 isnt mounting data partition fine

**Comment by yunxuan0530** [comment]
Ios 16 uses ramdisk15 to meet white apples

**Comment by ranzhie07** [comment]
same issue as mine its only happening in iphone x ios16 only

**Comment by ranzhie07** [comment]
> Yeah i don't know why ios 16 isnt mounting data partition fine

did you check the restored_external bro?

**Comment by ranzhie07** [comment]
same issue as mine its only happening in iphone x ios16 only. i tried iphone 8 ios 16 and mounting is working fine

**Comment by verygenericname** [comment]
pinned issue

**Comment by ranzhie07** [comment]
> pinned issue

Is this issue resolved bro?
