### ISSUE TITLE
in linux conection closed by remote host but in macos work nice and get ssh

### ISSUE THREAD

**Issue by Edwinnunez2004** [verygenericname/SSHRD_Script#83]
I have ubuntu and when I try getting ssh not work and that say "conection closed by remote host" so when i try with macos that work and i get ssh and i can mount partition and all work fine. the mac is not mine so i have ubuntu and i want to that work in ubuntu in order to request the mac

**Comment by verygenericname** [comment]
did you read the linux notes on the bottom of the README

**Comment by Edwinnunez2004** [comment]
> did you read the linux notes on the bottom of the README

yes my bro, i did all correctly 
and boot correctly and all but when i try ssh not work but in macos yes

**Comment by Edwinnunez2004** [comment]
what do you think about this, what could be the problem

**Comment by verygenericname** [comment]
Did you read the systemctl part

**Comment by Edwinnunez2004** [comment]
sorry, where systemctl is ?

**Comment by verygenericname** [comment]
Read the Linux notes part near the bottom of the README

**Comment by Edwinnunez2004** [comment]
ok my friend thank you

**Comment by Edwinnunez2004** [comment]
Jajaja my bro, very thank you, the problem was that I did not the readme Linux xd, I am stupid, I use that in order to try to boot dual-boot in ios 15 xd.
