### ISSUE TITLE
Error: file Firmware/*.dmg.trustcache does not exist, or is a directory

### ISSUE THREAD

**Issue by Merculous** [verygenericname/SSHRD_Script#85]
% ./sshrd.sh 8.3
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios8.3/058-14990-20150408-6F9D55BE-DAEB-11E4-956C-986C90F2D2C2/iPhone6,1_8.3_12F70_Restore.ipsw
init done
getting: BuildManifest.plist
100% [===================================================================================================>]
download succeeded
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios8.3/058-14990-20150408-6F9D55BE-DAEB-11E4-956C-986C90F2D2C2/iPhone6,1_8.3_12F70_Restore.ipsw
init done
getting: Firmware/dfu/iBSS.n51.RELEASE.im4p
100% [===================================================================================================>]
download succeeded
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios8.3/058-14990-20150408-6F9D55BE-DAEB-11E4-956C-986C90F2D2C2/iPhone6,1_8.3_12F70_Restore.ipsw
init done
getting: Firmware/dfu/iBEC.n51.RELEASE.im4p
100% [===================================================================================================>]
download succeeded
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios8.3/058-14990-20150408-6F9D55BE-DAEB-11E4-956C-986C90F2D2C2/iPhone6,1_8.3_12F70_Restore.ipsw
init done
getting: Firmware/all_flash/all_flash.n51ap.production/DeviceTree.n51ap.im4p
100% [===================================================================================================>]
download succeeded
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios8.3/058-14990-20150408-6F9D55BE-DAEB-11E4-956C-986C90F2D2C2/iPhone6,1_8.3_12F70_Restore.ipsw
init done
Error: file Firmware/058-14916-073.dmg.trustcache does not exist, or is a directory
[-] An error occurred
[-] uploading logs, if this fails, it's not a big deal.
ls: *.log: No such file or directory
curl: (26) Failed to open/read local data from file/application!

**Comment by verygenericname** [comment]
This ramdisk script is meant for ios 12+, sorry
