### ISSUE TITLE
Error: file Firmware/*.dmg.trustcache does not exist, or is a directory when trying to install Trollstore

### ISSUE THREAD

**Issue by azh97** [verygenericname/SSHRD_Script#94]
I ran the following command to install the Trollstore

`sudo bash ./sshrd.sh 15.7 TrollStore Tips`

But was greeted by the following error

<details>
<summary>Error</summary>
../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ../Linux/PlistBuddy)
../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ../Linux/PlistBuddy)
../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ../Linux/PlistBuddy)
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022FCSWinter/fullrestores/002-64404/755E570E-1FF2-40B2-B3C1-FE37D205687F/iPad_10.2_15.3.1_19D52_Restore.ipsw
init done
Error: file Firmware/.trustcache does not exist, or is a directory
[-] An error occurred
[-] uploading logs, if this fails, it's not a big deal.
mv: cannot stat '*.log': No such file or directory
</details>

Tried changing the iOS version, but same error appeared
Tried without bash, also same results

Device details :

iPad 7 10.2 (A2197)
iOS 15.3.1

Appreciate if someone could assist. Thanks.

**Comment by verygenericname** [comment]
update linux, also why are you trying to install trollstore on a ipad 7 on ios 10.2

**Comment by azh97** [comment]
Hi, thanks for getting back. Will try updating then. FYI I used the live version of linux. Also, ios version is 15.3.1. Sorry for the misunderstood.

**Comment by azh97** [comment]
I tried with Ubuntu 22.04.1 live, but received a different error as per below.
Any suggestions?

sudo ./sshrd.sh 15.3.1 TrollStore Tips
Archive:  gaster-Linux.zip
  inflating: gaster                  
[*] Getting device info... this may take a second
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9
^Csudo ./sshrd.sh 15.3.1 TrollStore Tips
Archive:  gaster-Linux.zip
  inflating: gaster                  
[*] Getting device info... this may take a second
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

**Comment by verygenericname** [comment]
That's irecovery crashing for some reason... not sure why

**Comment by azh97** [comment]
Yeah, for some reason my iPad restarted after it got stuck on

Getting device info... this may take a second

Deleting the SSHRD folder and retrying for god knows how many times, but ended up succeeding fortunately.
Thanks for your time! Updating Ubuntu did help!
