### ISSUE TITLE
[-] An error occured - latest commit

### ISSUE THREAD

**Issue by amats211** [verygenericname/SSHRD_Script#97]
Submodule 'sshtars' (https://github.com/verygenericname/sshtars) registered for path 'sshtars'
Cloning into '/Users/mac/Downloads/SSHRD_Script/sshtars'...
remote: Enumerating objects: 57, done.        
remote: Counting objects: 100% (22/22), done.        
remote: Compressing objects: 100% (13/13), done.        
remote: Total 57 (delta 14), reused 11 (delta 9), pack-reused 35        
Submodule path 'sshtars': checked out 'd1deb0d1661c681156907c93ef00d59391fd908b'
Macs-MacBook-Pro:SSHRD_Script mac$ ./sshrd.sh 15.0
[-] An error occurred
Macs-MacBook-Pro:SSHRD_Script mac$ ./sshrd.sh 15.7
[-] An error occurred
Macs-MacBook-Pro:SSHRD_Script mac$ sudo ./sshrd.sh 15.0
Password:
[-] An error occurred
Macs-MacBook-Pro:SSHRD_Script mac$ ./sshrd.sh https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-02953/B1EB01B7-DE28-4975-B294-49BAE9599E72/iPhone_4.7_P3_15.0_19A346_Restore.ipsw
[-] An error occurred
Macs-MacBook-Pro:SSHRD_Script mac$ sudo ./sshrd.sh 15.7
[-] An error occurred
Macs-MacBook-Pro:SSHRD_Script mac$ 

Device is an ip7..

**Comment by verygenericname** [comment]
What macOS version are you running

**Comment by amats211** [comment]
catalina

**Comment by itsnebulalol** [comment]
Update to big sur or later

**Comment by amats211** [comment]
hmm, unfortunately upgrade not possible with my machine..

**Comment by amats211** [comment]
tried to use an older commit and i think i got it to work.. will close this issue for now, thanks..
